import React from 'react';
import { Router, Route, Link, Switch } from 'react-router-dom';

import { history } from '@/_helpers';
import { authenticationService } from '@/_services';
import { PrivateRoute } from '@/_components';
import { HomePage } from '@/HomePage';
import { LoginPage } from '@/LoginPage';
import { LibaryPage } from '@/LibaryPage';
import logo from '../_images/logo.png';
class App extends React.Component {
    constructor(props) {
        super(props);

        this.state = {
            currentUser: null
        };
    }

    componentDidMount() {
        authenticationService.currentUser.subscribe(x => this.setState({ currentUser: x }));
    }

    logout() {
        authenticationService.logout();
        history.push('/login');
    }

    render() {
        const { currentUser } = this.state;
        return (
            <Router history={history}>
                <div>
                    {currentUser &&
                        <nav className="navbar navbar-expand navbar-dark bg-dark">
                            <div className="navbar-nav">
                            <Link to="/" className="nav-item nav-link">Home</Link>
                                <Link to="/libary" className="nav-item nav-link">Libary</Link>
                                <a onClick={this.logout} className="nav-item nav-link">Logout</a>
                            </div>
                        </nav>
                    }
                    <div className="jumbotron">
                        <div className="container">
                            <div className="text-center">
                                <img src={logo} className="rounded" alt="..." />
                                    </div>
                            <div className="text-center">Logo generated by <a className="text-center" href="https://www.designevo.com/logo-maker/" title="Free Online Logo Maker">DesignEvo free logo designer</a></div>
                            <div className="row">
                                <div className="col-md-12">
                                    <Route path="/login" component={LoginPage}/>
                                </div>
                            </div>
                        </div>
                    </div>
                    <Switch>
                        <PrivateRoute exact path="/" component={HomePage} />
                        {<Route path='/libary' component={LibaryPage} /> } 
                    </Switch>
                </div>
            </Router>
        );
    }
}

export { App }; 